### ISSUE TITLE
Google Drive integration throws error on overview page

### ISSUE THREAD

**Issue by johannesjo** [skddc/webmarks#84] opened 2020-05-13 09:01 UTC
1. Connect via Google Drive
2. Add a couple of webmarks
3. Go back to overview
4. Nothing shown on the screen and the console shows `Failed to load resource: the server responded with a status of 404 ()` for archive

![Screenshot from 2020-05-13 10-59-09](https://user-images.githubusercontent.com/1456265/81792795-d429af00-9508-11ea-9de1-6be2d7e6bae9.png)

**Comment by skddc** [comment] 2020-05-13 11:20
Thanks for the report!

Unfortunately, I cannot reproduce this error.

* Could you clarify how you would add multiple bookmarks without going back to the overview in between? The way it's described means that you were able to add the bookmarks without errors, so it would be important to know what happened then.
* I don't see a storage account being synced in the screenshot you posted. I don't understand why it would register a service worker when you merely navigate in a single-page app. The log looks like it's from loading the app, not from going back to the overview.

**Comment by skddc** [comment] 2020-05-13 11:22
... here's what a normal startup should look like btw:

![Screenshot from 2020-05-13 13-21-32](https://user-images.githubusercontent.com/842/81806455-c4b46100-951c-11ea-8361-50c55af22465.png)

If you don't show "rs.on ready", that means the entire app wasn't loaded correctly in the first place...

**Comment by johannesjo** [comment] 2020-05-13 12:19
Hmhm after logging back in the webmarks show up, but no `rs.on ready` or `rs.on connected`. The error is still there.
![Screenshot from 2020-05-13 14-12-31](https://user-images.githubusercontent.com/1456265/81810832-f5e45f80-9523-11ea-808b-ce52501eff9f.png)

After that I tried clearing all my storage and logging in. Which works. Then I tried deleting all entries which also works but throws `Cannot delete non-existing node /`. 

Seems to me that the error only occurs for freshly connected "empty" accounts.

**Comment by skddc** [comment] 2020-05-13 12:39
Ooh, could it be that you mixed up steps 1 and 2? That is, it fails when you add bookmarks, then connect an empty account?

**Comment by johannesjo** [comment] 2020-05-13 12:41
> Ooh, could it be that you mixed up steps 1 and 2? That is, it fails when you add bookmarks, and then connect an empty account?

No. I am pretty sure I connected before adding some new bookmarks.

**Comment by skddc** [comment] 2020-05-13 12:42
I remembered this error from before, and it turns out we fixed that long ago. It's only a log in the console now, but doesn't impact sync anymore:

https://github.com/remotestorage/remotestorage.js/issues/993
https://github.com/remotestorage/remotestorage.js/pull/1031

**Comment by skddc** [comment] 2020-05-13 12:43
Btw, what is the source that is linked for that weird 404 in your console?

**Comment by skddc** [comment] 2020-05-13 12:45
Actually, if you want, we can jump on a video call for debugging this. Maybe that's more efficient, as I cannot reproduce it on my machine. (I also deleted all bookmarks earlier when I tested this.)

**Comment by johannesjo** [comment] 2020-05-13 12:49
I am unable to reproduce both errors for a second time for some reason :/ Maybe it's possible to reproduce this with a fresh google account. I''ll check with removing the files and acceess for the app.

**Comment by johannesjo** [comment] 2020-05-13 12:59
No luck with that neither. Maybe with a fresh account?

We can do a video call but I am not sure it makes much sense when I am unable to reproduce the issue.

**Comment by skddc** [comment] 2020-05-13 13:46
> Maybe I had an ancient version cached locally?

Maybe. I switched from AppCache to ServiceWorker at some point after that fix.

As we both can't reproduce it at this point, I'll close this issue for now. Thanks anyway for opening it! And feel free to re-open anytime, of course.

**Closed** 2020-05-13 13:46 UTC
